<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" language="java"%>
<html lang="zh-CN">
<head>
<title></title>
<style>
@import "http://builder.oliv.cn/c/t2_1/c/src/_reset.css";
@import "http://builder.oliv.cn/c/t2_1/c/src/_emotion.css";
</style>
</head>
<body>
<div class="simi">
  <div class="simiT">
    <p><a href="#"><b>默认</b></a><a class="on" href="#"><b>流行</b></a><a href="#"><b>经典</b></a><a href="#"><b>节日</b></a></p>
  </div><div style="left: 0pt;" class="simiV"><i class="x x51"></i></div>
  <div style="display: none;" class="crJs_page">
  <div class="c stick"><a href="#"><i title="蜡烛" class="x x89_p"></i></a><a href="#"><i title="火鸡" class="x x52_p"></i></a><a href="#"><i title="唤醒" class="x x50_p"></i></a><a href="#"><i title="植物人" class="x x51_p"></i></a><a href="#"><i title="尖叫" class="x x46_p"></i></a><a href="#"><i title="神马" class="x x38_p"></i></a><a href="#"><i title="淡定" class="x x39_p"></i></a><a href="#"><i title="浮云" class="x x37_p"></i></a><a href="#"><i title="给力" class="x x40_p"></i></a><a href="#"><i title="飘过" class="x x43_p"></i></a><a href="#"><i title="围观" class="x x44_p"></i></a><a href="#"><i title="砖" class="x x32_p"></i></a></div>
  <div class="c"><a href="#"><i title="微笑" class="x x01_p"></i></a><a href="#"><i title="色" class="x x02_p"></i></a><a href="#"><i title="龇牙" class="x x03_p"></i></a><a href="#"><i title="偷笑" class="x x60_p"></i></a><a href="#"><i title="害羞" class="x x04_p"></i></a><a href="#"><i title="大哭" class="x x08_p"></i></a><a href="#"><i title="哭" class="x x63_p"></i></a><a href="#"><i title="酷" class="x x06_p"></i></a><a href="#"><i title="发火" class="x x09_p"></i></a><a href="#"><i title="怒" class="x x10_p"></i></a><a href="#"><i title="疑问" class="x x11_p"></i></a><a href="#"><i title="感叹" class="x x12_p"></i></a><a href="#"><i title="调皮" class="x x05_p"></i></a><a href="#"><i title="眨眼" class="x x70_p"></i></a><a href="#"><i title="寒" class="x x13_p"></i></a><a href="#"><i title="睡觉" class="x x15_p"></i></a><a href="#"><i title="困" class="x x73_p"></i></a><a href="#"><i title="不满" class="x x74_p"></i></a><a href="#"><i title="撅嘴" class="x x75_p"></i></a><a href="#"><i title="听歌" class="x x76_p"></i></a><a href="#"><i title="汗" class="x x07_p"></i></a><a href="#"><i title="脸红" class="x x78_p"></i></a><a href="#"><i title="耳语" class="x x79_p"></i></a><a href="#"><i title="嘘" class="x x80_p"></i></a><a href="#"><i title="吐" class="x x81_p"></i></a><a href="#"><i title="馋" class="x x82_p"></i></a><a href="#"><i title="鄙视" class="x x83_p"></i></a><a href="#"><i title="讽刺" class="x x84_p"></i></a><a href="#"><i title="发呆" class="x x85_p"></i></a><a href="#"><i title="晕" class="x x86_p"></i></a><a href="#"><i title="被踹" class="x x87_p"></i></a><a href="#"><i title="衰" class="x x88_p"></i></a><a href="#"><i title="受伤" class="x x56_p"></i></a><a href="#"><i title="海盗" class="x x57_p"></i></a><a href="#"><i title="闭嘴" class="x x14_p"></i></a><a href="#"><i title="佐罗" class="x x58_p"></i></a></div>
  </div>
  <div style="display:block;" class="crJs_page">
  <div class="c"><a href="#"><i title="蜡烛" class="x x89_p"></i></a><a href="#"><i title="唤醒" class="x x50_p"></i></a><a href="#"><i title="植物人" class="x x51_p"></i></a><a href="#"><i title="尖叫" class="x x46_p"></i></a><a href="#"><i title="神马" class="x x38_p"></i></a><a href="#"><i title="淡定" class="x x39_p"></i></a><a href="#"><i title="浮云" class="x x37_p"></i></a><a href="#"><i title="给力" class="x x40_p"></i></a><a href="#"><i title="飘过" class="x x43_p"></i></a><a href="#"><i title="围观" class="x x44_p"></i></a><a href="#"><i title="砖" class="x x32_p"></i></a><a href="#"><i title="？" class="x x33_p"></i></a><a href="#"><i title="国旗" class="x x36_p"></i></a><a href="#"><i title="金牌" class="x x49_p"></i></a><a href="#"><i title="进球" class="x x27_p"></i></a><a href="#"><i title="黑哨" class="x x28_p"></i></a><a href="#"><i title="黄牌" class="x x29_p"></i></a><a href="#"><i title="红牌" class="x x30_p"></i></a><a href="#"><i title="一" class="x x109_p"></i></a><a href="#"><i title="二" class="x x110_p"></i></a><a href="#"><i title="三" class="x x111_p"></i></a><a href="#"><i title="四" class="x x112_p"></i></a><a href="#"><i title="五" class="x x113_p"></i></a><a href="#"><i title="六" class="x x114_p"></i></a><a href="#"><i title="七" class="x x115_p"></i></a><a href="#"><i title="八" class="x x116_p"></i></a><a href="#"><i title="九" class="x x117_p"></i></a><a href="#"><i title="十" class="x x118_p"></i></a><a href="#"><i title="1潘" class="x x119_p"></i></a></div>
  </div>
  <div style="display:none;" class="crJs_page">
  <div class="c"><a href="#"><i title="爱" class="x x16_p"></i></a><a href="#"><i title="心碎" class="x x17_p"></i></a><a href="#"><i title="玫瑰" class="x x18_p"></i></a><a href="#"><i title="凋谢" class="x x19_p"></i></a><a href="#"><i title="顶" class="x x20_p"></i></a><a href="#"><i title="亲" class="x x21_p"></i></a><a href="#"><i title="想法" class="x x22_p"></i></a><a href="#"><i title="咖啡" class="x x23_p"></i></a><a href="#"><i title="西瓜" class="x x24_p"></i></a><a href="#"><i title="药" class="x x25_p"></i></a><a href="#"><i title="猪" class="x x26_p"></i></a><a href="#"><i title="握手" class="x x53_p"></i></a><a href="#"><i title="饭" class="x x54_p"></i></a><a href="#"><i title="鞭炮" class="x x55_p"></i></a><a href="#"><i title="胜利" class="x x59_p"></i></a><a href="#"><i title="烟" class="x x61_p"></i></a><a href="#"><i title="信" class="x x62_p"></i></a><a href="#"><i title="啤酒" class="x x64_p"></i></a><a href="#"><i title="钱" class="x x65_p"></i></a><a href="#"><i title="礼物" class="x x66_p"></i></a><a href="#"><i title="闹钟" class="x x67_p"></i></a><a href="#"><i title="电视" class="x x68_p"></i></a><a href="#"><i title="便便" class="x x69_p"></i></a><a href="#"><i title="月亮" class="x x71_p"></i></a><a href="#"><i title="手机" class="x x72_p"></i></a><a href="#"><i title="电话" class="x x77_p"></i></a></div>
  </div>
  <div style="display:none;" class="crJs_page">
  <div class="c"><a href="#"><i title="火鸡" class="x x52_p"></i></a><a href="#"><i title="樱桃" class="x x47_p"></i></a><a href="#"><i title="魔法师" class="x x45_p"></i></a><a href="#"><i title="南瓜" class="x x42_p"></i></a><a href="#"><i title="重阳" class="x x41_p"></i></a><a href="#"><i title="粽子" class="x x31_p"></i></a><a href="#"><i title="月饼" class="x x35_p"></i></a><a href="#"><i title="脱光" class="x x41_p"></i></a></div>
  </div>
</div>
</body>
</html>